### PR TITLE
feat(): offer to set the epub filename in url

### PR DESCRIPTION
**Pull request by oupala**
Add the capability to set the epub filename in the url parameter of the reader.

- `epub.js/reader/` to read the default epub
- `epub.js/reader/?book=moby-dick/` to read another epub
- `epub.js/reader/?book=moby-dick.epub` to read a compressed epub

epub files have been moved to a `books/` subdirectory in order to be easy to maintain (and separated from the epubjs codebase).

### CODE REVIEW

**Comment by oupala** [comment]
Are you willing to merge this request or not?

Is there a problem with my code? Should I improve it in a specific way?

**Comment by oupala** [comment]
If you do not plan to merge this pull request, I'd be pleased if you can tell me.

If you plan to merge this pull request, please do!

**Comment by fchasen** [comment]
So sorry for the delayed response on this.
In the reader you can override any of the setting using url parameters.

To set the books path you can set `bookPath=XXX` so for example:
http://futurepress.github.io/epub.js/reader/?bookPath=https://s3.amazonaws.com/epubjs/books/alice.epub

Does that work for your use case?

**Comment by oupala** [comment]
Thanks @fchasen for answering me.

I did not knew about the `bookPath` feature. Is it documented somewhere?

The main difference between the feature of my fork and the `bookPath` feature is that my feature was proposing to use a relative path from the `reader` path while the `bookPath` feature only allow to use absolute path.

Using absolute path might require to configure CORS (Cross Origin Ressource Sharing) which might be touchy.

Can you tell me if the `bookPath` feature is accepting relative path? If no, do you think you can improve the feature so it support relative paths?

**Comment by oupala** [comment]
In fact, the `bookPath` feature is allowing relative paths. So you can use paths relative to the reader directory.

**Pull request closed without merging**
