### PR TITLE
#942 Image and svg's max-width doesn't get set because of verticalPad…

### PR DESCRIPTION
**Pull request by tarungupta-in**
…ding

### CODE REVIEW

**Comment by tarungupta-in** [comment]
Hi @fchasen thanks for the amazing library, can you check this pull request and merge at your earliest convenience please, thanks

**Comment by llimos** [comment]
@tarungupta-in This change seems to make sense but the `verticalPadding` variable should be renamed to `horizontalPadding`

**Comment by fchasen** [comment]
My apologizes, I'll review this asap

**Comment by tarungupta-in** [comment]
Thanks @llimos for noticing, I have changed it to horizontalPadding, @fchasen Please review

**Comment by fchasen** [comment]
Sorry again for the delay getting this merged in, I'll get it deployed to NPM quickly

**Pull request merged**
