### PR TITLE
Fixed self closing html tags.

### PR DESCRIPTION
**Pull request by neciu**
According to pull request discussion: https://github.com/futurepress/epub.js/pull/288#issuecomment-146942234

### CODE REVIEW

**Comment by fchasen** [comment]
Ideally the responseXML should remain as it work just fine as it will parse HTML according to MDN: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/HTML_in_XMLHttpRequest.

Does the book you are using have HTML (instead of XHTML) files for the chapters?

if so I think this line is the culprit: https://github.com/neciu/epub.js/blob/123169ba7968aaa7215418512df1dfb5fe5e745c/src/core.js#L47

I should have a fix for this shortly but it requires changing around request a bit so that it detects the file extension, so I need test it a bit more.

**Comment by fchasen** [comment]
If you have a chance, could you try out this branch: https://github.com/futurepress/epub.js/tree/request_html

Hoping it will fix the issue behind the incorrect html parsing.

**Comment by neciu** [comment]
I've added this version (`git@github.com:futurepress/epub.js.git#a729c5`) to bower and run some tests.

Aaaaand the results are mixed :).

Your newest version works fine in browsers (as an normal app and mocha tests) but while running phantom tests I get errors related to parsing/DOM:

`Error: INVALID_STATE_ERR: DOM Exception 11` from: `epub.js:3487`

Related part of the file:
```
3486	if(type == 'xml') {
3487		xhr.responseType = "document";
3488		xhr.overrideMimeType('text/xml'); // for OPF parsing
3489	}
```

**Comment by fchasen** [comment]
Ah thanks - looks like I needed to move xhr `open` before `overrideMimeType`: http://stackoverflow.com/questions/12072315/uncaught-error-invalid-state-err-dom-exception-11

Should be fixed now.

**Comment by neciu** [comment]
Yea! It's working like a charm now. Thanks!

**Comment by neciu** [comment]
Ah! I forgot about one thing.

After last change in our Phantom tests `renderer:chapterDisplayed` event is not fired.

**Comment by fchasen** [comment]
Thanks again for helping to get HTML files to work properly, the changes are in 0.2.12.

Could you make a new issue for the "renderer:chapterDisplayed" not firing if you get a chance?

**Pull request closed without merging**
