### PR TITLE
examples/ie.html fix

### PR DESCRIPTION
**Pull request by pmstss**
- legacy zip library references replaced with new one (minified)
- locations.js included (no rendering without it)
- smartimages hook disabled (no rendering when it's enabled)
- remote jquery reference replaced with local
- few typos fixed, e.g. ie complained about missing space before class attribute in "next" arrow

### CODE REVIEW

**Comment by pmstss** [comment]
yes, it works in this way

**Comment by JakeHartnell** [comment]
This looks good to me. @fchasen want to press the button?

**Comment by fchasen** [comment]
Great - thanks again for the help with IE issues.

**Comment by fchasen** [comment]
Oops, I should have looked at this again.
Now that the compiled version is use we needed to remove:

```
<script src="../libs/jquery-2.1.0.js"></script>
<script src="../libs/underscore/underscore.js"></script>
<script src="../libs/rsvp/rsvp.js"></script>
<script src="../libs/fileStorage/fileStorage.min.js"></script>
```

Will push a fixed version.

**Pull request merged**
