### PR TITLE
Working backbone.html example

### PR DESCRIPTION
**Pull request by matewilk**
- working backbone example with hook example
- it can be run by adding bower.json file with the following dependencies (name and version doesn't amtter) :
```
{
  "name": "epub.js",
  "version": "0.0.1",
  "dependencies": {
    "jquery": "~2.1.0",
    "backbone": "~1.1.0",
    "handlebars": "~2.0.0"
  },
  "devDependencies": {
    
  }
}
```
- run "bower install" (if you have bower installed) - it will create bower_components dir with dependencies
- example is working!
- hook shows how you can select piece of text on pages (and how easy it is to create hooks)

### CODE REVIEW

**Comment by fchasen** [comment]
Thanks for fixing the backbone example, very much appreciated.

Could you squash these commits into one? It is hard to tell what changed currently.
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by matewilk** [comment]
Sorry, haven't noticed your comment on this. I'll do it this week. Sorry for the delay :)

**Comment by matewilk** [comment]
Hi, I hope this is what you were asking for? Let me know if it ready to merge!

**Comment by fchasen** [comment]
Perfect! Thanks so much.

**Comment by matewilk** [comment]
:+1: Let me know if there is anything else I can help you with :)

**Pull request merged**
