### PR TITLE
Adding a search method to section for find out result spanning multiple nodes.

### PR DESCRIPTION
**Pull request by lvscar**
Try to find result between previous and subsequent nodes

For example , finding "I beg" or "beg your pardon" or "i beg your" in following book section.
`<p>"Oh, I <i>beg</i> your pardon!" </p>  `
(from test/fixtures/alice/OPS/chapter_010.xhtml)

Test case added.

### CODE REVIEW

**Comment by fchasen** [comment]
This is very cool!

I don't want to modify `sprint` and `treeWalker`  to pass 3 nodes.
Could we create a `search` method that has the same structure as `sprint` but passes the prev and next node?

**Comment by lvscar** [comment]
Thanks for recommendation. I will try to implement the improvement in a new search method in next few days.

**Comment by lvscar** [comment]
I have implemented a new search method for section object. Current implementation keep the core.js untouched and have adopted a better strategy. (no more assume the result is in **3** nodes, but a configurable parameter )

And I have added compatibility test cases  (For keep search results are no difference with find )

**Comment by galgalesh** [comment]
Any update on this PR? This would be really useful.

**Comment by fchasen** [comment]
Looks perfect, sorry for the delay getting this merged.

**Pull request merged**
