### PR TITLE
Added some stuff to documentation

### PR DESCRIPTION
**Pull request by geek1011**
I have added pagination to the documentation, and a link to the tips and tricks page I created in the wiki.

### CODE REVIEW

**Comment by fchasen** [comment]
I'd rather not document using the pagination generation, as it is going to be removed in v0.3
It would be far better for most use cases to use locations generation (which we should document).

**Comment by geek1011** [comment]
Ok, I'll say it will be deprecated, and I will add location documentation. I think we should still leave the pagination documentation there because many people have trouble with that. Also, will there be a replacement for page numbers through pagination in 0.3?

On Nov 30, 2016 3:35 PM, Fred Chasen <notifications@github.com> wrote:

I'd rather not document using the pagination generation, as it is going to be removed in v0.3
It would be far better for most use cases to use locations generation (which we should document).

**Comment by fchasen** [comment]
That sounds perfect.

There won't be a method in v0.3 for generating the page numbers by rendering all chapters though that would still be possible. You'll be able to display location numbers or page number from a pageList instead.

**Comment by geek1011** [comment]
What is a location number? Will it be compatible with Calibre's reference number(spinePos.paragraph) (example: 5.21)?


On Thu, 1 Dec, 2016 at 11:48 AM, Fred Chasen <notifications@github.com> wrote:

That sounds perfect.

There won't be a method in v0.3 for generating the page numbers by rendering all chapters though that would still be possible. You'll be able to display location numbers or page number from a pageList instead.

**Comment by geek1011** [comment]
I have added a deprecation note to the pagination.

**Pull request merged**
