### PR TITLE
Format the layout when size of window has changed

### PR DESCRIPTION
**Pull request by gerhardsletten**
Should fix the issue with layout not updating if the size on window has resized

### CODE REVIEW

**Comment by fchasen** [comment]
Is that all it took? I'll try this out asap!

**Comment by gerhardsletten** [comment]
@fchasen think so..

**Comment by fchasen** [comment]
Works great 👍

**Comment by gerhardsletten** [comment]
Could you publish to npm as well?

**Comment by fchasen** [comment]
Published in `0.3.19`

**Pull request merged**
