### PR TITLE
IE fix querySelectorAll

### PR DESCRIPTION
**Pull request by mellenbe**
Fixes an IE issue that occurs for instance in the examples file contained.html:
"Could not load Chapter: OPS/cover.xhtml TypeError: [...]"

It seems that when applying the JS method querySelectorAll, IE does not distinguish between the selectors 'image' and 'img'. The 'image' selector finds img tags as well. This behaviour leads to the above-mentioned error. (The attribute "xlink:href" cannot be found in default img tags.)

(Tested in IE11)

### CODE REVIEW

**Comment by fchasen** [comment]
Thanks so much for figuring this out and submitting a PR.

Would it be possible to just scope the `image` queries to `svg` elements so that the query looked something like this: `document.querySelectorAll("svg image")` ?

**Comment by mellenbe** [comment]
You are right. This solution is of course much simpler and works also. Thank you! :)

**Comment by mellenbe** [comment]
I changed the query string (to "svg image") directly at its source at the invocation of the replaceWithStored method in replace.js and altered a string comparison in file chapter.js. The changed value does not seem to have any further implications.

**Comment by fchasen** [comment]
Perfect. Could you squash the commits into one? http://davidwalsh.name/squash-commits-git

**Comment by mellenbe** [comment]
Done!

**Comment by fchasen** [comment]
Great - thanks again for fixing this.

**Comment by mellenbe** [comment]
You are welcome!

**Pull request merged**
