### PR TITLE
Update Hypothesis integration

### PR DESCRIPTION
**Pull request by tilgovi**
@JakeHartnell

### CODE REVIEW

**Comment by tilgovi** [comment]
This gets things working again and simplifies the loading significantly, having only the annotator instance in the renderer frame and just embedding the iframe directly in the reader html.

Uses the `Book` interface for getting and setting the CFI when the annotations are opened.

Custom `Guest` to follow, possibly needing upstream changes, to get all the interactions right. First thing would be simply opening the annotations when the adder is used.

Also, the adder gets messed up on any page past the first of the chapter for me.

**Comment by fchasen** [comment]
This is greatI 

I need to take a look into the events a bit, as this seems to not trigger the change when it switches chapters.

And as you mentioned, the adder gets funky after the first page:

screen shot 2015-09-17 at 2 31 52 pm

**Comment by JakeHartnell** [comment]
@tilgovi THIS IS AWESOME! Thanks! : )

**Comment by fchasen** [comment]
Latest master fixes the second chapter issue by reloading the iframe on chapter unload by well still need to call `window.hypothesisInstall()` on each page load.

Something like this in the hook should work:
```
EPUBJS.core.addScript("//hypothes.is/embed.js", function() {
	renderer.render.window.hypothesisInstall();
	callback();
}, renderer.doc.head);
```

Seems like the adder just needs a width.

**Pull request merged**
