### PR TITLE
Support for IE 11

### PR DESCRIPTION
**Pull request by gerhardsletten**
Should fix support for IE11 #537

* Polyfill for url (it needs to be required in the library)
* And both support function and object with acceptNode function for treewalker

### CODE REVIEW

**Comment by fchasen** [comment]
There is already a url polyfill included in the legacy that has some specific functions Epubjs was using (though I can't remember off hand what they were). I'd prefer not to include that with the main code since it will be used in lots of places where it isn't needed.

TreeWalker fix looks good. Is it the same as https://github.com/futurepress/epub.js/pull/550 ?

**Comment by gerhardsletten** [comment]
@fchasen I was trying to get the v3 branch to work in IE11, and then I could not get the existing polyfill to work. And its probably better to use a package instead of keeping a copy. Whether it should be included like this, I am not sure. On one side we should support most used browsers, and for web-usage that would be important. But maybe we could expose a alternative entrypoint where shims are included, than if users use treeshaking the shim would not be bundled.

yes, the treewalking is probably the same

**Comment by fchasen** [comment]
I need to review the url.js and see what changed between the two.

Currently I just include url.js into the legacy build of js with the other polyfills from babel, but I guess there should be a way to use if you are including epub.js with imports / require.

**Comment by gerhardsletten** [comment]
> I need to review the url.js and see what changed between the two.

Yes, but looks like [url-polyfill](https://www.npmjs.com/package/url-polyfill) is updated, so I epubjs is not needing something not supported by it, I would guess its better to use it than keeping a own copy.

Think this is different than babels polyfills because they is mostly about never language features, and this is a browser feature not supported in every major browser. And if we could offer and extra entrypoint for this, it would be great. I could add that and maybe the README.md should be updated with this and basic usage in the v3 branch.

**Comment by fchasen** [comment]
I renamed `url.js` to `url-polyfill.js` and am including it by default now as it is used in enough different places that it seems better to always have it there in `epubjs@0.3.39`.

The current polyfill is from https://github.com/webcomponents/URL/blob/master/url.js but wrapped in a UMD loader, and with a fix for `file://` urls. It differs from the polyfill you added by not using an DOM elements to handle the url parsing, so it works in more contexts.

I can publish it a separate npm package is there is interest in that, otherwise it just lives in the libs folder.

**Pull request closed without merging**
