### PR TITLE
#465 to close stop render crash on missing assets

### PR DESCRIPTION
**Pull request by gimox**
Fix. render crash on missing assets

### CODE REVIEW

**Comment by fchasen** [comment]
Is this crashing the browser?

I think we still need to reject the request when a file isn't found and find what isn't handling the rejections correctly.

**Comment by gimox** [comment]
With this fix browser non crash and book render correctly. If image is missing it wil non diplayed. Some book have bad asset, some css declared and missing in assets. Most client reader render book, radiumterapie render the book, i think that epujs can non break reader on asset missing.

**Comment by fchasen** [comment]
That function should still reject if an asset isn't present in the zip.

We should handle the rejection better in the methods that are calling `getUrl ` and allow the rendering to continue.

https://github.com/futurepress/epub.js/blob/70fb1c957017db6010d77c541da889825aa88fb9/src/replace.js#L93 is a good example of how the other methods could be updated.

**Comment by fchasen** [comment]
I've just updated this on v0.3, where the promise rejection is still sent but handled by the replacements. Will need to update all the places `getUrl` is called to handle the rejection in v0.2.

**Pull request closed without merging**
