### PR TITLE
mathml hook fix, ie.html sample fix, support for ArrayBuffer as input

### PR DESCRIPTION
**Pull request by pmstss**
- change legacy zip.js references to JSZip in ie.html
- mathml hook fix: fixing access to renderer iframe (renderer.iframe -> renderer.render.iframe)
- support for bookPath argument in form of ArrayBuffer (e.g. for loading epub from file input control) with new example inputfile.html

### CODE REVIEW

**Comment by fchasen** [comment]
Thanks for this! Excited to be able to handle inputs.
I need to review ArrayBuffers a bit, my only hesitations is that having a bookPath that isn't a uri string is a bit confusing to me. Might need a different method to pass the contents of the books instead of a url.

**Comment by pmstss** [comment]
Thank you for the feedback! 
I agree that using ArrayBuffer with naming bookPath is confusing. I also see that in v0.3 there is single url argument in constructor - have no ideas how to embed this ArrayBuffer there. Please give a hint to do it better for both versions. 
Btw, what are the main differences between master (v0.2) and v0.3? Are there any doc/wiki describing major differences, or only git log and sources?
These are my first pull requests on github, if i'm doing something incorrectly - please let me know.

**Comment by JakeHartnell** [comment]
@pmstss if you separate out the mathml hook fix and ie.html sample fix into a different PR, we can merge those.

**Comment by pmstss** [comment]
ok, will do this nearest time

**Comment by pmstss** [comment]
created #253 for mathml. 
ie has stopped working after updating from upstream - will do more tries.

**Comment by pmstss** [comment]
clarified; created #254 and #255 for basic-dev.html and ie.html respectively

**Comment by pmstss** [comment]
inputfile.html demo is now available separately in #256

**Pull request closed without merging**
