### PR TITLE
Respect pre-paginated page spreads

### PR DESCRIPTION
**Pull request by mikkelvp**

### CODE REVIEW

**Comment by fchasen** [comment]
Sorry for the delay reviewing this. Is there an epub I can test it with?

**Comment by mikkelvp** [comment]
Sent you an email.

**Comment by fchasen** [comment]
Sorry again for the delay on this, thanks for making these fixes - they look great.

**Comment by johnfactotum** [comment]
This PR works great! But there's a slight issue when going directly to a spine item with the property `page-spread-right` with `rendition.display()`.

The issue can be reproduced like so:
1. Open the book ["Page Blanche"](https://github.com/IDPF/epub3-samples/releases/download/20170606/page-blanche.epub) from [EPUB 3 Samples](https://idpf.github.io/epub3-samples/30/samples.html) with Epub.js 0.3.87
2. Run `rendition.display(6)`
  Actual result: section 6 is displayed on the right side, but the left side is empty
  Expected result: section 6 on the right and section 5 on the left 
2. Now run `rendition.prev()`
  Actual result: section 5 shows up on the right, and section 4 on the left
  Expected result: section 4 on the right, and section 3 on the left

**Comment by mikkelvp** [comment]
@johnfactotum I'm aware of this. I will look into it sometime in the future.

**Pull request merged**
