### PR TITLE
Potential fix for wrong page being displayed sometimes.

### PR DESCRIPTION
**Pull request by tushar9989**
https://github.com/futurepress/epub.js/issues/895
https://github.com/futurepress/epub.js/issues/691

### CODE REVIEW

**Comment by fchasen** [comment]
Thanks for this. I'll clone this and give it a try

**Comment by vlatri** [comment]
Hey, is this going to get merged?

**Comment by sengemann** [comment]
Any anyone else encountered errors since this fix? Version `0.3.83` seems to be the last stable version. I'm attempting to load an Epub to a cover page via epubCIFrange (`epubcfi(/6/2[cover]!/4)`) and when line `590` is called (`range.setEnd`), no such method exists on the range object. I'm getting the error 

`contents.js:593 setting end offset to start container length failed DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 19.`

There has been at least one other error reported similar to this: https://github.com/futurepress/epub.js/issues/895#issuecomment-516264652

**Comment by tushar9989** [comment]
This is just reported in the console, it is wrapped with a try catch.

**Comment by sengemann** [comment]
When this error occurs, the book no longer navigates. This is more than just a "reported in the console" thing.

**Comment by tushar9989** [comment]
Can you share the book so that I can look into it.

**Comment by qtv100291** [comment]
Still stuck on this issue, after changing font size by using rendition.themes.fontSize, rendition.display sometimes doesn't show right location of a cfi.

**Pull request merged**
